### ISSUE TITLE
Choice of test library

### ISSUE THREAD

**Issue by caulagi** [wyze/wyze.github.io#10]
I am curious as to why you choose to write tests with `bs-react-testing-library` instead of `bs-react-test-renderer` like in reason-calculator. I am new to reason and react and learning it as I go along by browsing github; and hence the question.

One difference seems to me that it is not possible to test the meta-tags in ReactHelmet components when using `bs-react-testing-library`. Thanks.

**Comment by wyze** [comment]
This is newer and reason-calculator is a little dated. I've been meaning to go back and get it up to date and switch to `bs-react-testing-library`.

If you look at the tests for `reason-calculator` you will notice they are all snapshots. Going into the snapshot files, they all look the same. There isn't a good way currently to provide useful snapshots in Reason.

Given the above, I plan to switch to `bs-react-testing-library` in `reason-calculator` very soon.

**Comment by caulagi** [comment]
Thanks!
